apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-webapi
  template:
    metadata:
      labels:
        app: dotnet-webapi
    spec:
      containers:
      - name: dotnet-webapi
        image: k8shealth:0.3
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /healthz/startup
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
