#@K8s_healthcheck_HostAddress = http://localhost:5027

@K8s_healthcheck_HostAddress = http://127.0.0.1:8080/

POST  http://127.0.0.1:8080/healthz/status?isLive=true&isReady=true

###
POST  http://127.0.0.1:8080/healthz/status?isLive=false&isReady=false

###
POST  http://localhost:5027/healthz/status?isLive=false&isReady=false